# Generated by Django 3.1.1 on 2020-10-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active_team',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
